In [51]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [52]:
np.random.seed(42)
n=10000
df = pd.DataFrame({
    "Age" :np.random.randint(17,26,n),
    "Gender" : np.random.choice(["Male","Female"],n),
    "Attendance" : np.random.randint(40,101,n),
    "CGPA" : np.round(np.random.uniform(4.5,10,n),2),
    "Backlogs" : np.random.randint(0,8,n),
    "FamilyIncome": np.random.randint(15000,2000000,n),
   # "StudyHours" : np.round(np.random.uniform(0.5,8,n),
    "StudyHours": np.round(np.random.uniform(0.5, 8, n), 2),
    "Schlorship": np.random.choice([0,1],n,p=[0.7,0.3]),
    "InternetAcess" : np.random.choice([0,1],n,p=[0.15,0.85]),
    "Hostel" : np.random.choice([0,1],n),
    "MentalStress": np.random.randint(1,11,n),
    "PartTimejob" : np.random.choice([0,1],n,p=[0.75,0.25])
 })

In [53]:
risk = (
    (df["Attendance"] <65).astype(int) +
    (df["CGPA"] <6.0).astype(int) +
    (df["Backlogs"] >=3).astype(int) +
    (df["MentalStress"]>=8).astype(int) +
    (df["StudyHours"] <2).astype(int) 
)

df["Dropout"] = np.where(risk>=3,1,0)

In [54]:
df

,Age,Gender,Attendance,CGPA,Backlogs,FamilyIncome,StudyHours,Schlorship,InternetAcess,Hostel,MentalStress,PartTimejob,Dropout
0,23,Female,70,5.71,3,512769,7.73,0,1,0,2,0,0
1,20,Female,45,6.17,6,268202,4.38,1,1,0,3,0,0
2,24,Male,53,5.21,7,642807,4.79,1,1,1,1,1,1
3,21,Female,97,5.87,0,1505601,5.50,0,1,0,8,1,0
4,23,Male,62,9.02,2,511632,6.48,0,1,0,6,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,17,Female,70,4.77,6,1161551,5.48,0,1,0,10,0,1
9996,23,Male,48,7.05,5,1139568,3.07,0,1,1,5,0,0
9997,22,Male,61,9.10,0,1184896,5.22,0,0,0,5,0,0
9998,25,Female,50,5.49,5,367406,2.38,1,1,1,6,0,1
9999,23,Female,56,5.30,5,579012,2.69,1,1,0,8,0,1

In [55]:
X = df.drop("Dropout",axis=1)
y = df["Dropout"]

In [56]:
X = pd.get_dummies(X,drop_first=True)

In [57]:
X

,Age,Attendance,CGPA,Backlogs,FamilyIncome,StudyHours,Schlorship,InternetAcess,Hostel,MentalStress,PartTimejob,Gender_Male
0,23,70,5.71,3,512769,7.73,0,1,0,2,0,False
1,20,45,6.17,6,268202,4.38,1,1,0,3,0,False
2,24,53,5.21,7,642807,4.79,1,1,1,1,1,True
3,21,97,5.87,0,1505601,5.50,0,1,0,8,1,False
4,23,62,9.02,2,511632,6.48,0,1,0,6,0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,17,70,4.77,6,1161551,5.48,0,1,0,10,0,False
9996,23,48,7.05,5,1139568,3.07,0,1,1,5,0,True
9997,22,61,9.10,0,1184896,5.22,0,0,0,5,0,True
9998,25,50,5.49,5,367406,2.38,1,1,1,6,0,False
9999,23,56,5.30,5,579012,2.69,1,1,0,8,0,False

In [58]:
X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 41,
    stratify=y
)

In [59]:
X_train.shape

(8000, 12)

In [60]:
X_test.shape

(2000, 12)

In [61]:
y_train.shape

(8000,)

In [62]:
y_test.shape

(2000,)

In [69]:
pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Collecting xgboost
  Using cached xgboost-3.3.0-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.3.0-py3-none-win_amd64.whl (69.5 MB)
   ---------------------------------------- 0.0/69.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/69.5 MB ? eta -:--:--
   ---------------------------------------- 0.8/69.5 MB 2.4 MB/s eta 0:00:30
    --------------------------------------- 1.6/69.5 MB 3.0 MB/s eta 0:00:23
   - -------------------------------------- 1.8/69.5 MB 2.9 MB/s eta 0:00:24
   - -------------------------------------- 2.1/69.5 MB 2.3 MB/s eta 0:00:29
   - -------------------------------------- 2.1/69.5 MB 2.3 MB/s eta 0:00:29
   - -------------------------------------- 2.4/69.5 MB 1.9 MB/s eta 0:00:36
   - -------------------------------------- 2.4/69.5 MB 1.9 MB/s eta 0:00:36
   - -------------------------------------- 2.6/69.5 MB 1.5 MB/s eta 0:00:46
   - -------------------------------------- 2.6/69.5 MB 1.5 MB/s eta 0:00:46
   - -------------------------------------- 2.9/69.5 MB 1.3 MB/s eta 0:00:52
   - -------------------------------------- 2.9/69.5 MB 1.3 MB/s eta 0:00:52
   - -------------------------------------- 3.4/69.5 MB 1.2 MB/s eta 0:00:55
   -- ------------------------------------- 3.7/69.5 MB 1.2 MB/s eta 0:00:54
   -- ------------------------------------- 3.9/69.5 MB 1.2 MB/s eta 0:00:53
   -- ------------------------------------- 4.2/69.5 MB 1.2 MB/s eta 0:00:54
   -- ------------------------------------- 4.5/69.5 MB 1.2 MB/s eta 0:00:54
   -- ------------------------------------- 4.7/69.5 MB 1.2 MB/s eta 0:00:54
   -- ------------------------------------- 5.0/69.5 MB 1.2 MB/s eta 0:00:52
   --- ------------------------------------ 5.5/69.5 MB 1.3 MB/s eta 0:00:50
   --- ------------------------------------ 5.8/69.5 MB 1.3 MB/s eta 0:00:50
   --- ------------------------------------ 6.3/69.5 MB 1.3 MB/s eta 0:00:48
   --- ------------------------------------ 6.6/69.5 MB 1.3 MB/s eta 0:00:48
   --- ------------------------------------ 6.8/69.5 MB 1.3 MB/s eta 0:00:48
   ---- ----------------------------------- 7.3/69.5 MB 1.4 MB/s eta 0:00:46
   ---- ----------------------------------- 8.1/69.5 MB 1.4 MB/s eta 0:00:43
   ---- ----------------------------------- 8.7/69.5 MB 1.5 MB/s eta 0:00:41
   ----- ---------------------------------- 9.4/69.5 MB 1.6 MB/s eta 0:00:39
   ----- ---------------------------------- 9.7/69.5 MB 1.6 MB/s eta 0:00:39
   ----- ---------------------------------- 9.7/69.5 MB 1.6 MB/s eta 0:00:39
   ----- ---------------------------------- 10.0/69.5 MB 1.5 MB/s eta 0:00:40
   ----- ---------------------------------- 10.2/69.5 MB 1.5 MB/s eta 0:00:40
   ------ --------------------------------- 10.5/69.5 MB 1.5 MB/s eta 0:00:40
   ------ --------------------------------- 10.7/69.5 MB 1.5 MB/s eta 0:00:40
   ------ --------------------------------- 10.7/69.5 MB 1.5 MB/s eta 0:00:40
   ------ --------------------------------- 11.0/69.5 MB 1.5 MB/s eta 0:00:41
   ------ --------------------------------- 11.5/69.5 MB 1.4 MB/s eta 0:00:41
   ------ --------------------------------- 12.1/69.5 MB 1.5 MB/s eta 0:00:39
   ------- -------------------------------- 12.8/69.5 MB 1.5 MB/s eta 0:00:38
   ------- -------------------------------- 13.6/69.5 MB 1.6 MB/s eta 0:00:36
   -------- ------------------------------- 14.2/69.5 MB 1.6 MB/s eta 0:00:35
   -------- ------------------------------- 14.4/69.5 MB 1.6 MB/s eta 0:00:35
   -------- ------------------------------- 14.9/69.5 MB 1.6 MB/s eta 0:00:34
   --------- ------------------------------ 15.7/69.5 MB 1.7 MB/s eta 0:00:33
   --------- ------------------------------ 16.5/69.5 MB 1.7 MB/s eta 0:00:32
   --------- ------------------------------ 17.0/69.5 MB 1.7 MB/s eta 0:00:31
   ---------- ----------------------------- 17.8/69.5 MB 1.8 MB/s eta 0:00:30
   ---------- ----------------------------- 18.4/69.5 MB 1.8 MB/s eta 0:00:29
   ----------- ---------------------------- 19.1/69.5 MB 1.8 MB/s eta 0:00:28
   ----------- ---------------------------- 19.9/69.5 MB 1.9 MB/s eta 0:00:27
   ----------- ---------------------------- 20.4/69.5 MB 1.9 MB/s eta 0:00:27
   ------------ --------------------------- 21.0/69.5 MB 1.9 MB/s eta 0:00:26
   ------------ --------------------------- 21.2/69.5 MB 1.9 MB/s eta 0:00:26
   ------------ --------------------------- 21.5/69.5 MB 1.9 MB/s eta 0:00:26
   ------------ --------------------------- 21.8/69.5 MB 1.9 MB/s eta 0:00:26
   ------------ --------------------------- 22.0/69.5 MB 1.8 MB/s eta 0:00:27
   ------------ --------------------------- 22.0/69.5 MB 1.8 MB/s eta 0:00:27
   ------------ --------------------------- 22.0/69.5 MB 1.8 MB/s eta 0:00:27
   ------------ --------------------------- 22.3/69.5 MB 1.8 MB/s eta 0:00:27
   ------------ --------------------------- 22.3/69.5 MB 1.8 MB/s eta 0:00:27
   ------------ --------------------------- 22.3/69.5 MB 1.8 MB/s eta 0:00:27
   ------------ --------------------------- 22.5/69.5 MB 1.7 MB/s eta 0:00:28
   ------------ --------------------------- 22.5/69.5 MB 1.7 MB/s eta 0:00:28
   ------------- -------------------------- 22.8/69.5 MB 1.7 MB/s eta 0:00:29
   ------------- -------------------------- 23.1/69.5 MB 1.6 MB/s eta 0:00:29
   ------------- -------------------------- 23.3/69.5 MB 1.6 MB/s eta 0:00:29
   ------------- -------------------------- 23.6/69.5 MB 1.6 MB/s eta 0:00:29
   ------------- -------------------------- 23.9/69.5 MB 1.6 MB/s eta 0:00:29
   ------------- -------------------------- 24.1/69.5 MB 1.6 MB/s eta 0:00:28
   -------------- ------------------------- 24.4/69.5 MB 1.6 MB/s eta 0:00:28
   -------------- ------------------------- 24.6/69.5 MB 1.6 MB/s eta 0:00:28
   -------------- ------------------------- 24.9/69.5 MB 1.6 MB/s eta 0:00:28
   -------------- ------------------------- 25.4/69.5 MB 1.6 MB/s eta 0:00:28
   -------------- ------------------------- 25.7/69.5 MB 1.6 MB/s eta 0:00:28
   -------------- ------------------------- 26.0/69.5 MB 1.6 MB/s eta 0:00:28
   --------------- ------------------------ 26.2/69.5 MB 1.6 MB/s eta 0:00:28
   --------------- ------------------------ 26.5/69.5 MB 1.6 MB/s eta 0:00:28
   --------------- ------------------------ 26.5/69.5 MB 1.6 MB/s eta 0:00:28
   --------------- ------------------------ 26.5/69.5 MB 1.6 MB/s eta 0:00:28
   --------------- ------------------------ 26.7/69.5 MB 1.6 MB/s eta 0:00:28
   --------------- ------------------------ 27.0/69.5 MB 1.5 MB/s eta 0:00:28
   --------------- ------------------------ 27.5/69.5 MB 1.5 MB/s eta 0:00:28
   --------------- ------------------------ 27.8/69.5 MB 1.6 MB/s eta 0:00:27
   ---------------- ----------------------- 28.0/69.5 MB 1.6 MB/s eta 0:00:27
   ---------------- ----------------------- 28.6/69.5 MB 1.6 MB/s eta 0:00:27
   ---------------- ----------------------- 28.8/69.5 MB 1.6 MB/s eta 0:00:27
   ---------------- ----------------------- 29.1/69.5 MB 1.6 MB/s eta 0:00:26
   ---------------- ----------------------- 29.4/69.5 MB 1.6 MB/s eta 0:00:26
   ---------------- ----------------------- 29.4/69.5 MB 1.6 MB/s eta 0:00:26
   ----------------- ---------------------- 29.6/69.5 MB 1.5 MB/s eta 0:00:27
   ----------------- ---------------------- 29.6/69.5 MB 1.5 MB/s eta 0:00:27
   ----------------- ---------------------- 29.6/69.5 MB 1.5 MB/s eta 0:00:27
   ----------------- ---------------------- 29.9/69.5 MB 1.5 MB/s eta 0:00:27
   ----------------- ---------------------- 29.9/69.5 MB 1.5 MB/s eta 0:00:27
   ----------------- ---------------------- 30.1/69.5 MB 1.5 MB/s eta 0:00:27
   ----------------- ---------------------- 30.4/69.5 MB 1.5 MB/s eta 0:00:27
   ----------------- ---------------------- 30.7/69.5 MB 1.5 MB/s eta 0:00:27
   ----------------- ---------------------- 30.9/69.5 MB 1.5 MB/s eta 0:00:27
   ------------------ --------------------- 31.5/69.5 MB 1.5 MB/s eta 0:00:27
   ------------------ --------------------- 31.7/69.5 MB 1.5 MB/s eta 0:00:26
   ------------------ --------------------- 32.0/69.5 MB 1.5 MB/s eta 0:00:26
   ------------------ --------------------- 32.8/69.5 MB 1.5 MB/s eta 0:00:25
   ------------------- -------------------- 33.3/69.5 MB 1.5 MB/s eta 0:00:25
   ------------------- -------------------- 33.6/69.5 MB 1.5 MB/s eta 0:00:25
   ------------------- -------------------- 33.8/69.5 MB 1.5 MB/s eta 0:00:25
   ------------------- -------------------- 34.1/69.5 MB 1.5 MB/s eta 0:00:24
   ------------------- -------------------- 34.3/69.5 MB 1.5 MB/s eta 0:00:24
   -------------------- ------------------- 34.9/69.5 MB 1.5 MB/s eta 0:00:24
   -------------------- ------------------- 35.4/69.5 MB 1.5 MB/s eta 0:00:23
   -------------------- ------------------- 35.7/69.5 MB 1.5 MB/s eta 0:00:23
   -------------------- ------------------- 36.2/69.5 MB 1.5 MB/s eta 0:00:23
   --------------------- ------------------ 36.7/69.5 MB 1.5 MB/s eta 0:00:22
   --------------------- ------------------ 37.5/69.5 MB 1.5 MB/s eta 0:00:21
   --------------------- ------------------ 38.0/69.5 MB 1.5 MB/s eta 0:00:21
   ---------------------- ----------------- 38.3/69.5 MB 1.5 MB/s eta 0:00:21
   ---------------------- ----------------- 38.8/69.5 MB 1.5 MB/s eta 0:00:20
   ---------------------- ----------------- 39.3/69.5 MB 1.6 MB/s eta 0:00:20
   ---------------------- ----------------- 39.8/69.5 MB 1.6 MB/s eta 0:00:20
   ---------------------- ----------------- 39.8/69.5 MB 1.6 MB/s eta 0:00:20
   ----------------------- ---------------- 40.1/69.5 MB 1.6 MB/s eta 0:00:19
   ----------------------- ---------------- 40.6/69.5 MB 1.5 MB/s eta 0:00:19
   ----------------------- ---------------- 40.9/69.5 MB 1.5 MB/s eta 0:00:19
   ----------------------- ---------------- 41.2/69.5 MB 1.5 MB/s eta 0:00:19
   ----------------------- ---------------- 41.4/69.5 MB 1.5 MB/s eta 0:00:19
   ------------------------ --------------- 41.9/69.5 MB 1.5 MB/s eta 0:00:18
   ------------------------ --------------- 42.2/69.5 MB 1.5 MB/s eta 0:00:18
   ------------------------ --------------- 42.5/69.5 MB 1.5 MB/s eta 0:00:18
   ------------------------ --------------- 42.7/69.5 MB 1.5 MB/s eta 0:00:18
   ------------------------ --------------- 43.0/69.5 MB 1.5 MB/s eta 0:00:18
   ------------------------ --------------- 43.3/69.5 MB 1.5 MB/s eta 0:00:18
   ------------------------- -------------- 43.5/69.5 MB 1.5 MB/s eta 0:00:17
   ------------------------- -------------- 43.8/69.5 MB 1.5 MB/s eta 0:00:17
   ------------------------- -------------- 44.3/69.5 MB 1.5 MB/s eta 0:00:17
   ------------------------- -------------- 44.8/69.5 MB 1.5 MB/s eta 0:00:17
   -------------------------- ------------- 45.4/69.5 MB 1.5 MB/s eta 0:00:16
   -------------------------- ------------- 45.6/69.5 MB 1.6 MB/s eta 0:00:16
   -------------------------- ------------- 45.9/69.5 MB 1.5 MB/s eta 0:00:16
   -------------------------- ------------- 46.4/69.5 MB 1.6 MB/s eta 0:00:15
   -------------------------- ------------- 46.9/69.5 MB 1.6 MB/s eta 0:00:15
   --------------------------- ------------ 47.7/69.5 MB 1.6 MB/s eta 0:00:14
   --------------------------- ------------ 48.2/69.5 MB 1.6 MB/s eta 0:00:14
   --------------------------- ------------ 48.5/69.5 MB 1.6 MB/s eta 0:00:14
   ---------------------------- ----------- 49.0/69.5 MB 1.6 MB/s eta 0:00:14
   ---------------------------- ----------- 49.3/69.5 MB 1.6 MB/s eta 0:00:13
   ---------------------------- ----------- 49.8/69.5 MB 1.6 MB/s eta 0:00:13
   ---------------------------- ----------- 50.1/69.5 MB 1.6 MB/s eta 0:00:13
   ---------------------------- ----------- 50.1/69.5 MB 1.6 MB/s eta 0:00:13
   ----------------------------- ---------- 50.6/69.5 MB 1.6 MB/s eta 0:00:12
   ----------------------------- ---------- 51.1/69.5 MB 1.6 MB/s eta 0:00:12
   ----------------------------- ---------- 51.6/69.5 MB 1.6 MB/s eta 0:00:12
   ------------------------------ --------- 52.2/69.5 MB 1.6 MB/s eta 0:00:11
   ------------------------------ --------- 52.7/69.5 MB 1.6 MB/s eta 0:00:11
   ------------------------------ --------- 53.2/69.5 MB 1.6 MB/s eta 0:00:10
   ------------------------------ --------- 53.7/69.5 MB 1.7 MB/s eta 0:00:10
   ------------------------------- -------- 54.3/69.5 MB 1.7 MB/s eta 0:00:10
   ------------------------------- -------- 55.1/69.5 MB 1.7 MB/s eta 0:00:09
   ------------------------------- -------- 55.3/69.5 MB 1.7 MB/s eta 0:00:09
   -------------------------------- ------- 55.8/69.5 MB 1.7 MB/s eta 0:00:09
   -------------------------------- ------- 56.4/69.5 MB 1.7 MB/s eta 0:00:08
   -------------------------------- ------- 56.9/69.5 MB 1.7 MB/s eta 0:00:08
   -------------------------------- ------- 56.9/69.5 MB 1.7 MB/s eta 0:00:08
   -------------------------------- ------- 57.1/69.5 MB 1.7 MB/s eta 0:00:08
   -------------------------------- ------- 57.1/69.5 MB 1.7 MB/s eta 0:00:08
   --------------------------------- ------ 57.4/69.5 MB 1.6 MB/s eta 0:00:08
   --------------------------------- ------ 57.4/69.5 MB 1.6 MB/s eta 0:00:08
   --------------------------------- ------ 57.4/69.5 MB 1.6 MB/s eta 0:00:08
   --------------------------------- ------ 57.7/69.5 MB 1.6 MB/s eta 0:00:08
   --------------------------------- ------ 57.7/69.5 MB 1.6 MB/s eta 0:00:08
   --------------------------------- ------ 57.9/69.5 MB 1.6 MB/s eta 0:00:08
   --------------------------------- ------ 57.9/69.5 MB 1.6 MB/s eta 0:00:08
   --------------------------------- ------ 58.2/69.5 MB 1.6 MB/s eta 0:00:08
   --------------------------------- ------ 58.5/69.5 MB 1.6 MB/s eta 0:00:07
   --------------------------------- ------ 58.5/69.5 MB 1.6 MB/s eta 0:00:07
   --------------------------------- ------ 58.7/69.5 MB 1.6 MB/s eta 0:00:07
   --------------------------------- ------ 59.0/69.5 MB 1.6 MB/s eta 0:00:07
   ---------------------------------- ----- 59.2/69.5 MB 1.6 MB/s eta 0:00:07
   ---------------------------------- ----- 59.5/69.5 MB 1.6 MB/s eta 0:00:07
   ---------------------------------- ----- 60.0/69.5 MB 1.6 MB/s eta 0:00:07
   ---------------------------------- ----- 60.0/69.5 MB 1.6 MB/s eta 0:00:07
   ---------------------------------- ----- 60.3/69.5 MB 1.5 MB/s eta 0:00:07
   ---------------------------------- ----- 60.6/69.5 MB 1.5 MB/s eta 0:00:06
   ----------------------------------- ---- 61.1/69.5 MB 1.5 MB/s eta 0:00:06
   ----------------------------------- ---- 61.3/69.5 MB 1.5 MB/s eta 0:00:06
   ----------------------------------- ---- 61.3/69.5 MB 1.5 MB/s eta 0:00:06
   ----------------------------------- ---- 61.6/69.5 MB 1.5 MB/s eta 0:00:06
   ----------------------------------- ---- 61.6/69.5 MB 1.5 MB/s eta 0:00:06
   ----------------------------------- ---- 61.9/69.5 MB 1.4 MB/s eta 0:00:06
   ----------------------------------- ---- 62.1/69.5 MB 1.4 MB/s eta 0:00:06
   ----------------------------------- ---- 62.4/69.5 MB 1.4 MB/s eta 0:00:06
   ----------------------------------- ---- 62.4/69.5 MB 1.4 MB/s eta 0:00:06
   ----------------------------------- ---- 62.4/69.5 MB 1.4 MB/s eta 0:00:06
   ------------------------------------ --- 62.7/69.5 MB 1.4 MB/s eta 0:00:05
   ------------------------------------ --- 62.9/69.5 MB 1.4 MB/s eta 0:00:05
   ------------------------------------ --- 62.9/69.5 MB 1.4 MB/s eta 0:00:05
   ------------------------------------ --- 63.2/69.5 MB 1.4 MB/s eta 0:00:05
   ------------------------------------ --- 63.4/69.5 MB 1.4 MB/s eta 0:00:05
   ------------------------------------ --- 63.7/69.5 MB 1.4 MB/s eta 0:00:05
   ------------------------------------ --- 64.2/69.5 MB 1.4 MB/s eta 0:00:04
   ------------------------------------- -- 64.5/69.5 MB 1.4 MB/s eta 0:00:04
   ------------------------------------- -- 64.5/69.5 MB 1.4 MB/s eta 0:00:04
   ------------------------------------- -- 64.7/69.5 MB 1.4 MB/s eta 0:00:04
   ------------------------------------- -- 65.3/69.5 MB 1.4 MB/s eta 0:00:03
   ------------------------------------- -- 65.3/69.5 MB 1.4 MB/s eta 0:00:03
   ------------------------------------- -- 65.3/69.5 MB 1.4 MB/s eta 0:00:03
   ------------------------------------- -- 65.3/69.5 MB 1.4 MB/s eta 0:00:03
   ------------------------------------- -- 65.5/69.5 MB 1.4 MB/s eta 0:00:03
   ------------------------------------- -- 65.8/69.5 MB 1.4 MB/s eta 0:00:03
   ------------------------------------- -- 65.8/69.5 MB 1.4 MB/s eta 0:00:03
   ------------------------------------- -- 65.8/69.5 MB 1.4 MB/s eta 0:00:03
   ------------------------------------- -- 65.8/69.5 MB 1.4 MB/s eta 0:00:03
   -------------------------------------- - 66.1/69.5 MB 1.4 MB/s eta 0:00:03
   -------------------------------------- - 66.1/69.5 MB 1.4 MB/s eta 0:00:03
   -------------------------------------- - 66.3/69.5 MB 1.4 MB/s eta 0:00:03
   -------------------------------------- - 66.3/69.5 MB 1.4 MB/s eta 0:00:03
   -------------------------------------- - 66.3/69.5 MB 1.4 MB/s eta 0:00:03
   -------------------------------------- - 66.6/69.5 MB 1.4 MB/s eta 0:00:03
   -------------------------------------- - 66.8/69.5 MB 1.3 MB/s eta 0:00:02
   -------------------------------------- - 67.1/69.5 MB 1.3 MB/s eta 0:00:02
   -------------------------------------- - 67.4/69.5 MB 1.4 MB/s eta 0:00:02
   ---------------------------------------  67.9/69.5 MB 1.4 MB/s eta 0:00:02
   ---------------------------------------  67.9/69.5 MB 1.4 MB/s eta 0:00:02
   ---------------------------------------  68.2/69.5 MB 1.3 MB/s eta 0:00:02
   ---------------------------------------  68.4/69.5 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  68.4/69.5 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  68.9/69.5 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  68.9/69.5 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  69.2/69.5 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------  69.5/69.5 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 69.5/69.5 MB 1.3 MB/s  0:00:49
Installing collected packages: xgboost
Successfully installed xgboost-3.3.0
Note: you may need to restart the kernel to use updated packages.

In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB

In [72]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "KNN":KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC(),
    "XGBoost": XGBClassifier(),
    "Naive Bayes": GaussianNB()  
}

In [73]:
result = []
for name, model in models.items():
    model.fit(X_train, y_train)
    pred = model.predict(X_test)

In [74]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

results = []

for name, model in models.items():

    # Train
    model.fit(X_train, y_train)

    # Predict class labels
    y_pred = model.predict(X_test)

    # Predict probabilities
    if hasattr(model, "predict_proba"):
        y_prob = model.predict_proba(X_test)[:, 1]
    else:
        # SVM without probability=True
        y_prob = y_pred

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred),
        "ROC AUC": roc_auc_score(y_test, y_prob)
    })

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [75]:
result_df = pd.DataFrame(results)
result_df = result_df.sort_values(
    by="Accuracy",
    ascending = False
)
result_df

                 Model  Accuracy  Precision    Recall  F1 Score   ROC AUC
2        Decision Tree    1.0000   1.000000  1.000000  1.000000  1.000000
3        Random Forest    1.0000   1.000000  1.000000  1.000000  1.000000
5              XGBoost    1.0000   1.000000  1.000000  1.000000  1.000000
0  Logistic Regression    0.8510   0.727047  0.609148  0.662896  0.912976
4                  SVM    0.7595   0.000000  0.000000  0.000000  0.500000
6          Naive Bayes    0.7595   0.000000  0.000000  0.000000  0.742367
1                  KNN    0.7035   0.233333  0.101871  0.141823  0.497403