In [107]:
import numpy as np
import pandas as pd
np.random.seed(45)
n_student =10000
data ={
    "name" : np.random.choice(["dev","riya","shagun","poonam"]),
    "age" : np.random.randint(15,30,n_student),
    "city" : np.random.choice(["ynr","radaur","ambala"])
}
df=pd.DataFrame(data)

In [108]:
df

        name  age    city
0     poonam   29  ambala
1     poonam   18  ambala
2     poonam   27  ambala
3     poonam   15  ambala
4     poonam   28  ambala
...      ...  ...     ...
9995  poonam   15  ambala
9996  poonam   26  ambala
9997  poonam   22  ambala
9998  poonam   15  ambala
9999  poonam   18  ambala

[10000 rows x 3 columns]

In [109]:
import sqlite3 as sql
import pandas as pd

In [113]:
connection = sql.connect('demo4.db')

In [114]:
cursor = connection.cursor()

In [115]:
cursor.execute('''CREATE TABLE data(
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER,
    city TEXT
);''')

In [116]:
connection.commit()

In [117]:
data1= list(df.itertuples(index=False, name= None))
cursor.executemany('''INSERT INTO data(name,age,city) VALUES (?,?,?)''',data1)

#cursor.execute('''INSERT INTO people(name,age,city)VALUES ('riya',19);''')

In [118]:
connection.commit()

In [119]:
cursor.execute('''SELECT*FROM data''')

In [120]:
results = cursor.fetchall()

In [121]:
for record in results:
    print(record)

(1, 'poonam', 29, 'ambala')
(2, 'poonam', 18, 'ambala')
(3, 'poonam', 27, 'ambala')
(4, 'poonam', 15, 'ambala')
(5, 'poonam', 28, 'ambala')
(6, 'poonam', 20, 'ambala')
(7, 'poonam', 18, 'ambala')
(8, 'poonam', 19, 'ambala')
(9, 'poonam', 24, 'ambala')
(10, 'poonam', 23, 'ambala')
(11, 'poonam', 16, 'ambala')
(12, 'poonam', 29, 'ambala')
(13, 'poonam', 20, 'ambala')
(14, 'poonam', 24, 'ambala')
(15, 'poonam', 21, 'ambala')
(16, 'poonam', 23, 'ambala')
(17, 'poonam', 22, 'ambala')
(18, 'poonam', 29, 'ambala')
(19, 'poonam', 23, 'ambala')
(20, 'poonam', 20, 'ambala')
(21, 'poonam', 27, 'ambala')
(22, 'poonam', 17, 'ambala')
(23, 'poonam', 27, 'ambala')
(24, 'poonam', 23, 'ambala')
(25, 'poonam', 27, 'ambala')
(26, 'poonam', 16, 'ambala')
(27, 'poonam', 21, 'ambala')
(28, 'poonam', 19, 'ambala')
(29, 'poonam', 29, 'ambala')
(30, 'poonam', 29, 'ambala')
(31, 'poonam', 29, 'ambala')
(32, 'poonam', 23, 'ambala')
(33, 'poonam', 29, 'ambala')
(34, 'poonam', 25, 'ambala')
(35, 'poonam', 19, 'ambala')
(36, 'poonam', 21, 'ambala')
(37, 'poonam', 19, 'ambala')
(38, 'poonam', 24, 'ambala')
(39, 'poonam', 28, 'ambala')
(40, 'poonam', 16, 'ambala')
(41, 'poonam', 21, 'ambala')
(42, 'poonam', 27, 'ambala')
(43, 'poonam', 25, 'ambala')
(44, 'poonam', 26, 'ambala')
(45, 'poonam', 23, 'ambala')
(46, 'poonam', 23, 'ambala')
(47, 'poonam', 16, 'ambala')
(48, 'poonam', 28, 'ambala')
(49, 'poonam', 26, 'ambala')
(50, 'poonam', 26, 'ambala')
(51, 'poonam', 28, 'ambala')
(52, 'poonam', 25, 'ambala')
(53, 'poonam', 21, 'ambala')
(54, 'poonam', 15, 'ambala')
(55, 'poonam', 19, 'ambala')
(56, 'poonam', 24, 'ambala')
(57, 'poonam', 23, 'ambala')
(58, 'poonam', 15, 'ambala')
(59, 'poonam', 24, 'ambala')
(60, 'poonam', 17, 'ambala')
(61, 'poonam', 21, 'ambala')
(62, 'poonam', 22, 'ambala')
(63, 'poonam', 26, 'ambala')
(64, 'poonam', 15, 'ambala')
(65, 'poonam', 15, 'ambala')
(66, 'poonam', 26, 'ambala')
(67, 'poonam', 25, 'ambala')
(68, 'poonam', 17, 'ambala')
(69, 'poonam', 27, 'ambala')
(70, 'poonam', 24, 'ambala')
(71, 'poonam', 17, 'ambala')
(72, 'poonam', 21, 'ambala')
(73, 'poonam', 15, 'ambala')
(74, 'poonam', 24, 'ambala')
(75, 'poonam', 21, 'ambala')
(76, 'poonam', 15, 'ambala')
(77, 'poonam', 23, 'ambala')
(78, 'poonam', 23, 'ambala')
(79, 'poonam', 15, 'ambala')
(80, 'poonam', 26, 'ambala')
(81, 'poonam', 21, 'ambala')
(82, 'poonam', 27, 'ambala')
(83, 'poonam', 22, 'ambala')
(84, 'poonam', 23, 'ambala')
(85, 'poonam', 20, 'ambala')
(86, 'poonam', 26, 'ambala')
(87, 'poonam', 16, 'ambala')
(88, 'poonam', 28, 'ambala')
(89, 'poonam', 18, 'ambala')
(90, 'poonam', 22, 'ambala')
(91, 'poonam', 27, 'ambala')
(92, 'poonam', 20, 'ambala')
(93, 'poonam', 24, 'ambala')
(94, 'poonam', 18, 'ambala')
(95, 'poonam', 26, 'ambala')
(96, 'poonam', 29, 'ambala')
(97, 'poonam', 17, 'ambala')
(98, 'poonam', 22, 'ambala')
(99, 'poonam', 22, 'ambala')
(100, 'poonam', 19, 'ambala')
(101, 'poonam', 24, 'ambala')
(102, 'poonam', 24, 'ambala')
(103, 'poonam', 24, 'ambala')
(104, 'poonam', 26, 'ambala')
(105, 'poonam', 24, 'ambala')
(106, 'poonam', 27, 'ambala')
(107, 'poonam', 22, 'ambala')
(108, 'poonam', 25, 'ambala')
(109, 'poonam', 17, 'ambala')
(110, 'poonam', 22, 'ambala')
(111, 'poonam', 24, 'ambala')
(112, 'poonam', 29, 'ambala')
(113, 'poonam', 29, 'ambala')
(114, 'poonam', 19, 'ambala')
(115, 'poonam', 20, 'ambala')
(116, 'poonam', 22, 'ambala')
(117, 'poonam', 26, 'ambala')
(118, 'poonam', 27, 'ambala')
(119, 'poonam', 27, 'ambala')
(120, 'poonam', 24, 'ambala')
(121, 'poonam', 22, 'ambala')
(122, 'poonam', 21, 'ambala')
(123, 'poonam', 17, 'ambala')
(124, 'poonam', 22, 'ambala')
(125, 'poonam', 22, 'ambala')
(126, 'poonam', 21, 'ambala')
(127, 'poonam', 26, 'ambala')
(128, 'poonam', 26, 'ambala')
(129, 'poonam', 21, 'ambala')
(130, 'poonam', 28, 'ambala')
(131, 'poonam', 18, 'ambala')
(132, 'poonam', 21, 'ambala')
(133, 'poonam', 15, 'ambala')
(134, 'poonam', 29, 'ambala')
(135, 'poonam', 27, 'ambala')
(136, 'poonam', 22, 'ambala')
(137, 'poonam', 19, 'ambala')
(138, 'poonam', 24, 'ambala')
(139, 'poonam', 18, 'ambala')
(140, 'poonam', 28, 'ambala')
(141, 'poonam', 20, 'ambala')
(142, 'poonam', 25, 'ambala')
(143, 'poonam', 22, 'ambala')
(144, 'poonam', 18, 'ambala')
(145, 'poonam', 20, 'ambala')
(146, 'poonam', 20, 'ambala')
(147, 'poonam', 22, 'ambala')
(148, 'poonam', 29, 'ambala')
(149, 'poonam', 16, 'ambala')
(150, 'poonam', 15, 'ambala')
(151, 'poonam', 17, 'ambala')
(152, 'poonam', 26, 'ambala')
(153, 'poonam', 26, 'ambala')
(154, 'poonam', 16, 'ambala')
(155, 'poonam', 29, 'ambala')
(156, 'poonam', 26, 'ambala')
(157, 'poonam', 24, 'ambala')
(158, 'poonam', 27, 'ambala')
(159, 'poonam', 27, 'ambala')
(160, 'poonam', 17, 'ambala')
(161, 'poonam', 25, 'ambala')
(162, 'poonam', 28, 'ambala')
(163, 'poonam', 18, 'ambala')
(164, 'poonam', 24, 'ambala')
(165, 'poonam', 21, 'ambala')
(166, 'poonam', 18, 'ambala')
(167, 'poonam', 26, 'ambala')
(168, 'poonam', 29, 'ambala')
(169, 'poonam', 21, 'ambala')
(170, 'poonam', 16, 'ambala')
(171, 'poonam', 24, 'ambala')
(172, 'poonam', 16, 'ambala')
(173, 'poonam', 22, 'ambala')
(174, 'poonam', 19, 'ambala')
(175, 'poonam', 15, 'ambala')
(176, 'poonam', 25, 'ambala')
(177, 'poonam', 17, 'ambala')
(178, 'poonam', 16, 'ambala')
(179, 'poonam', 25, 'ambala')
(180, 'poonam', 27, 'ambala')
(181, 'poonam', 16, 'ambala')
(182, 'poonam', 19, 'ambala')
(183, 'poonam', 25, 'ambala')
(184, 'poonam', 17, 'ambala')
(185, 'poonam', 26, 'ambala')
(186, 'poonam', 17, 'ambala')
(187, 'poonam', 26, 'ambala')
(188, 'poonam', 17, 'ambala')
(189, 'poonam', 26, 'ambala')
(190, 'poonam', 20, 'ambala')
(191, 'poonam', 26, 'ambala')
(192, 'poonam', 18, 'ambala')
(193, 'poonam', 21, 'ambala')
(194, 'poonam', 22, 'ambala')
(195, 'poonam', 20, 'ambala')
(196, 'poonam', 29, 'ambala')
(197, 'poonam', 21, 'ambala')
(198, 'poonam', 20, 'ambala')
(199, 'poonam', 27, 'ambala')
(200, 'poonam', 17, 'ambala')
(201, 'poonam', 29, 'ambala')
(202, 'poonam', 29, 'ambala')
(203, 'poonam', 23, 'ambala')
(204, 'poonam', 28, 'ambala')
(205, 'poonam', 22, 'ambala')
(206, 'poonam', 25, 'ambala')
(207, 'poonam', 16, 'ambala')
(208, 'poonam', 17, 'ambala')
(209, 'poonam', 27, 'ambala')
(210, 'poonam', 22, 'ambala')
(211, 'poonam', 24, 'ambala')
(212, 'poonam', 21, 'ambala')
(213, 'poonam', 27, 'ambala')
(214, 'poonam', 19, 'ambala')
(215, 'poonam', 26, 'ambala')
(216, 'poonam', 28, 'ambala')
(217, 'poonam', 20, 'ambala')
(218, 'poonam', 28, 'ambala')
(219, 'poonam', 19, 'ambala')
(220, 'poonam', 20, 'ambala')
(221, 'poonam', 26, 'ambala')
(222, 'poonam', 25, 'ambala')
(223, 'poonam', 19, 'ambala')
(224, 'poonam', 16, 'ambala')
(225, 'poonam', 18, 'ambala')
(226, 'poonam', 22, 'ambala')
(227, 'poonam', 15, 'ambala')
(228, 'poonam', 20, 'ambala')
(229, 'poonam', 26, 'ambala')
(230, 'poonam', 27, 'ambala')
(231, 'poonam', 15, 'ambala')
(232, 'poonam', 21, 'ambala')
(233, 'poonam', 20, 'ambala')
(234, 'poonam', 25, 'ambala')
(235, 'poonam', 27, 'ambala')
(236, 'poonam', 23, 'ambala')
(237, 'poonam', 26, 'ambala')
(238, 'poonam', 27, 'ambala')
(239, 'poonam', 25, 'ambala')
(240, 'poonam', 28, 'ambala')
(241, 'poonam', 29, 'ambala')
(242, 'poonam', 15, 'ambala')
(243, 'poonam', 16, 'ambala')
(244, 'poonam', 24, 'ambala')
(245, 'poonam', 29, 'ambala')
(246, 'poonam', 24, 'ambala')
(247, 'poonam', 17, 'ambala')
(248, 'poonam', 19, 'ambala')
(249, 'poonam', 19, 'ambala')
(250, 'poonam', 15, 'ambala')
(251, 'poonam', 23, 'ambala')
(252, 'poonam', 17, 'ambala')
(253, 'poonam', 23, 'ambala')
(254, 'poonam', 24, 'ambala')
(255, 'poonam', 22, 'ambala')
(256, 'poonam', 20, 'ambala')
(257, 'poonam', 27, 'ambala')
(258, 'poonam', 19, 'ambala')
(259, 'poonam', 27, 'ambala')
(260, 'poonam', 28, 'ambala')
(261, 'poonam', 18, 'ambala')
(262, 'poonam', 25, 'ambala')
(263, 'poonam', 17, 'ambala')
(264, 'poonam', 26, 'ambala')
(265, 'poonam', 20, 'ambala')
(266, 'poonam', 22, 'ambala')
(267, 'poonam', 28, 'ambala')
(268, 'poonam', 26, 'ambala')
(269, 'poonam', 24, 'ambala')
(270, 'poonam', 17, 'ambala')
(271, 'poonam', 20, 'ambala')
(272, 'poonam', 23, 'ambala')
(273, 'poonam', 15, 'ambala')
(274, 'poonam', 23, 'ambala')
(275, 'poonam', 24, 'ambala')
(276, 'poonam', 26, 'ambala')
(277, 'poonam', 27, 'ambala')
(278, 'poonam', 28, 'ambala')
(279, 'poonam', 19, 'ambala')
(280, 'poonam', 15, 'ambala')
(281, 'poonam', 25, 'ambala')
(282, 'poonam', 17, 'ambala')
(283, 'poonam', 20, 'ambala')
(284, 'poonam', 25, 'ambala')
(285, 'poonam', 16, 'ambala')
(286, 'poonam', 25, 'ambala')
(287, 'poonam', 29, 'ambala')
(288, 'poonam', 26, 'ambala')
(289, 'poonam', 17, 'ambala')
(290, 'poonam', 16, 'ambala')
(291, 'poonam', 19, 'ambala')
(292, 'poonam', 17, 'ambala')
(293, 'poonam', 29, 'ambala')
(294, 'poonam', 18, 'ambala')
(295, 'poonam', 22, 'ambala')
(296, 'poonam', 15, 'ambala')
(297, 'poonam', 17, 'ambala')
(298, 'poonam', 28, 'ambala')
(299, 'poonam', 15, 'ambala')
(300, 'poonam', 25, 'ambala')
(301, 'poonam', 23, 'ambala')
(302, 'poonam', 23, 'ambala')
(303, 'poonam', 27, 'ambala')
(304, 'poonam', 26, 'ambala')
(305, 'poonam', 21, 'ambala')
(306, 'poonam', 26, 'ambala')
(307, 'poonam', 23, 'ambala')
(308, 'poonam', 22, 'ambala')
(309, 'poonam', 20, 'ambala')
(310, 'poonam', 17, 'ambala')
(311, 'poonam', 26, 'ambala')
(312, 'poonam', 24, 'ambala')
(313, 'poonam', 17, 'ambala')
(314, 'poonam', 18, 'ambala')
(315, 'poonam', 17, 'ambala')
(316, 'poonam', 20, 'ambala')
(317, 'poonam', 29, 'ambala')
(318, 'poonam', 22, 'ambala')
(319, 'poonam', 23, 'ambala')
(320, 'poonam', 23, 'ambala')
(321, 'poonam', 24, 'ambala')
(322, 'poonam', 16, 'ambala')
(323, 'poonam', 25, 'ambala')
(324, 'poonam', 27, 'ambala')
(325, 'poonam', 19, 'ambala')
(326, 'poonam', 24, 'ambala')
(327, 'poonam', 29, 'ambala')
(328, 'poonam', 20, 'ambala')
(329, 'poonam', 16, 'ambala')
(330, 'poonam', 27, 'ambala')
(331, 'poonam', 24, 'ambala')
(332, 'poonam', 18, 'ambala')
(333, 'poonam', 15, 'ambala')
(334, 'poonam', 20, 'ambala')
(335, 'poonam', 19, 'ambala')
(336, 'poonam', 25, 'ambala')
(337, 'poonam', 23, 'ambala')
(338, 'poonam', 17, 'ambala')
(339, 'poonam', 27, 'ambala')
(340, 'poonam', 21, 'ambala')
(341, 'poonam', 16, 'ambala')
(342, 'poonam', 19, 'ambala')
(343, 'poonam', 25, 'ambala')
(344, 'poonam', 19, 'ambala')
(345, 'poonam', 15, 'ambala')
(346, 'poonam', 29, 'ambala')
(347, 'poonam', 24, 'ambala')
(348, 'poonam', 18, 'ambala')
(349, 'poonam', 26, 'ambala')
(350, 'poonam', 27, 'ambala')
(351, 'poonam', 15, 'ambala')
(352, 'poonam', 24, 'ambala')
(353, 'poonam', 27, 'ambala')
(354, 'poonam', 29, 'ambala')
(355, 'poonam', 20, 'ambala')
(356, 'poonam', 18, 'ambala')
(357, 'poonam', 26, 'ambala')
(358, 'poonam', 25, 'ambala')
(359, 'poonam', 18, 'ambala')
(360, 'poonam', 22, 'ambala')
(361, 'poonam', 20, 'ambala')
(362, 'poonam', 16, 'ambala')
(363, 'poonam', 25, 'ambala')
(364, 'poonam', 18, 'ambala')
(365, 'poonam', 22, 'ambala')
(366, 'poonam', 16, 'ambala')
(367, 'poonam', 24, 'ambala')
(368, 'poonam', 26, 'ambala')
(369, 'poonam', 18, 'ambala')
(370, 'poonam', 28, 'ambala')
(371, 'poonam', 28, 'ambala')
(372, 'poonam', 27, 'ambala')
(373, 'poonam', 20, 'ambala')
(374, 'poonam', 27, 'ambala')
(375, 'poonam', 15, 'ambala')
(376, 'poonam', 16, 'ambala')
(377, 'poonam', 15, 'ambala')
(378, 'poonam', 27, 'ambala')
(379, 'poonam', 25, 'ambala')
(380, 'poonam', 22, 'ambala')
(381, 'poonam', 16, 'ambala')
(382, 'poonam', 25, 'ambala')
(383, 'poonam', 16, 'ambala')
(384, 'poonam', 22, 'ambala')
(385, 'poonam', 20, 'ambala')
(386, 'poonam', 21, 'ambala')
(387, 'poonam', 26, 'ambala')
(388, 'poonam', 26, 'ambala')
(389, 'poonam', 29, 'ambala')
(390, 'poonam', 18, 'ambala')
(391, 'poonam', 19, 'ambala')
(392, 'poonam', 15, 'ambala')
(393, 'poonam', 22, 'ambala')
(394, 'poonam', 19, 'ambala')
(395, 'poonam', 26, 'ambala')
(396, 'poonam', 28, 'ambala')
(397, 'poonam', 15, 'ambala')
(398, 'poonam', 29, 'ambala')
(399, 'poonam', 16, 'ambala')
(400, 'poonam', 26, 'ambala')
(401, 'poonam', 17, 'ambala')
(402, 'poonam', 29, 'ambala')
(403, 'poonam', 22, 'ambala')
(404, 'poonam', 23, 'ambala')
(405, 'poonam', 17, 'ambala')
(406, 'poonam', 20, 'ambala')
(407, 'poonam', 23, 'ambala')
(408, 'poonam', 15, 'ambala')
(409, 'poonam', 23, 'ambala')
(410, 'poonam', 28, 'ambala')
(411, 'poonam', 18, 'ambala')
(412, 'poonam', 25, 'ambala')
(413, 'poonam', 20, 'ambala')
(414, 'poonam', 22, 'ambala')
(415, 'poonam', 29, 'ambala')
(416, 'poonam', 26, 'ambala')
(417, 'poonam', 29, 'ambala')
(418, 'poonam', 20, 'ambala')
(419, 'poonam', 19, 'ambala')
(420, 'poonam', 15, 'ambala')
(421, 'poonam', 23, 'ambala')
(422, 'poonam', 27, 'ambala')
(423, 'poonam', 24, 'ambala')
(424, 'poonam', 24, 'ambala')
(425, 'poonam', 15, 'ambala')
(426, 'poonam', 22, 'ambala')
(427, 'poonam', 23, 'ambala')
(428, 'poonam', 16, 'ambala')
(429, 'poonam', 25, 'ambala')
(430, 'poonam', 15, 'ambala')
(431, 'poonam', 21, 'ambala')
(432, 'poonam', 20, 'ambala')
(433, 'poonam', 25, 'ambala')
(434, 'poonam', 23, 'ambala')
(435, 'poonam', 16, 'ambala')
(436, 'poonam', 22, 'ambala')
(437, 'poonam', 28, 'ambala')
(438, 'poonam', 23, 'ambala')
(439, 'poonam', 17, 'ambala')
(440, 'poonam', 26, 'ambala')
(441, 'poonam', 16, 'ambala')
(442, 'poonam', 27, 'ambala')
(443, 'poonam', 16, 'ambala')
(444, 'poonam', 18, 'ambala')
(445, 'poonam', 21, 'ambala')
(446, 'poonam', 18, 'ambala')
(447, 'poonam', 17, 'ambala')
(448, 'poonam', 25, 'ambala')
(449, 'poonam', 26, 'ambala')
(450, 'poonam', 23, 'ambala')
(451, 'poonam', 18, 'ambala')
(452, 'poonam', 17, 'ambala')
(453, 'poonam', 23, 'ambala')
(454, 'poonam', 21, 'ambala')
(455, 'poonam', 23, 'ambala')
(456, 'poonam', 28, 'ambala')
(457, 'poonam', 17, 'ambala')
(458, 'poonam', 16, 'ambala')
(459, 'poonam', 15, 'ambala')
(460, 'poonam', 29, 'ambala')
(461, 'poonam', 26, 'ambala')
(462, 'poonam', 16, 'ambala')
(463, 'poonam', 21, 'ambala')
(464, 'poonam', 16, 'ambala')
(465, 'poonam', 18, 'ambala')
(466, 'poonam', 27, 'ambala')
(467, 'poonam', 22, 'ambala')
(468, 'poonam', 17, 'ambala')
(469, 'poonam', 28, 'ambala')
(470, 'poonam', 16, 'ambala')
(471, 'poonam', 18, 'ambala')
(472, 'poonam', 29, 'ambala')
(473, 'poonam', 23, 'ambala')
(474, 'poonam', 23, 'ambala')
(475, 'poonam', 17, 'ambala')
(476, 'poonam', 29, 'ambala')
(477, 'poonam', 27, 'ambala')
(478, 'poonam', 22, 'ambala')
(479, 'poonam', 25, 'ambala')
(480, 'poonam', 19, 'ambala')
(481, 'poonam', 25, 'ambala')
(482, 'poonam', 20, 'ambala')
(483, 'poonam', 20, 'ambala')
(484, 'poonam', 28, 'ambala')
(485, 'poonam', 29, 'ambala')
(486, 'poonam', 23, 'ambala')
(487, 'poonam', 22, 'ambala')
(488, 'poonam', 29, 'ambala')
(489, 'poonam', 15, 'ambala')
(490, 'poonam', 29, 'ambala')
(491, 'poonam', 16, 'ambala')
(492, 'poonam', 17, 'ambala')
(493, 'poonam', 21, 'ambala')
(494, 'poonam', 18, 'ambala')
(495, 'poonam', 23, 'ambala')
(496, 'poonam', 27, 'ambala')
(497, 'poonam', 16, 'ambala')
(498, 'poonam', 28, 'ambala')
(499, 'poonam', 19, 'ambala')
(500, 'poonam', 28, 'ambala')
(501, 'poonam', 15, 'ambala')
(502, 'poonam', 22, 'ambala')
(503, 'poonam', 28, 'ambala')
(504, 'poonam', 19, 'ambala')
(505, 'poonam', 23, 'ambala')
(506, 'poonam', 21, 'ambala')
(507, 'poonam', 29, 'ambala')
(508, 'poonam', 18, 'ambala')
(509, 'poonam', 27, 'ambala')
(510, 'poonam', 23, 'ambala')
(511, 'poonam', 15, 'ambala')
(512, 'poonam', 19, 'ambala')
(513, 'poonam', 19, 'ambala')
(514, 'poonam', 18, 'ambala')
(515, 'poonam', 15, 'ambala')
(516, 'poonam', 24, 'ambala')
(517, 'poonam', 20, 'ambala')
(518, 'poonam', 21, 'ambala')
(519, 'poonam', 16, 'ambala')
(520, 'poonam', 22, 'ambala')
(521, 'poonam', 22, 'ambala')
(522, 'poonam', 29, 'ambala')
(523, 'poonam', 22, 'ambala')
(524, 'poonam', 23, 'ambala')
(525, 'poonam', 23, 'ambala')
(526, 'poonam', 29, 'ambala')
(527, 'poonam', 20, 'ambala')
(528, 'poonam', 22, 'ambala')
(529, 'poonam', 15, 'ambala')
(530, 'poonam', 27, 'ambala')
(531, 'poonam', 27, 'ambala')
(532, 'poonam', 24, 'ambala')
(533, 'poonam', 18, 'ambala')
(534, 'poonam', 19, 'ambala')
(535, 'poonam', 22, 'ambala')
(536, 'poonam', 23, 'ambala')
(537, 'poonam', 24, 'ambala')
(538, 'poonam', 23, 'ambala')
(539, 'poonam', 19, 'ambala')
(540, 'poonam', 27, 'ambala')
(541, 'poonam', 25, 'ambala')
(542, 'poonam', 18, 'ambala')
(543, 'poonam', 24, 'ambala')
(544, 'poonam', 27, 'ambala')
(545, 'poonam', 28, 'ambala')
(546, 'poonam', 19, 'ambala')
(547, 'poonam', 17, 'ambala')
(548, 'poonam', 19, 'ambala')
(549, 'poonam', 19, 'ambala')
(550, 'poonam', 20, 'ambala')
(551, 'poonam', 26, 'ambala')
(552, 'poonam', 18, 'ambala')
(553, 'poonam', 29, 'ambala')
(554, 'poonam', 29, 'ambala')
(555, 'poonam', 24, 'ambala')
(556, 'poonam', 28, 'ambala')
(557, 'poonam', 24, 'ambala')
(558, 'poonam', 19, 'ambala')
(559, 'poonam', 26, 'ambala')
(560, 'poonam', 28, 'ambala')
(561, 'poonam', 17, 'ambala')
(562, 'poonam', 26, 'ambala')
(563, 'poonam', 16, 'ambala')
(564, 'poonam', 20, 'ambala')
(565, 'poonam', 24, 'ambala')
(566, 'poonam', 18, 'ambala')
(567, 'poonam', 24, 'ambala')
(568, 'poonam', 28, 'ambala')
(569, 'poonam', 28, 'ambala')
(570, 'poonam', 24, 'ambala')
(571, 'poonam', 27, 'ambala')
(572, 'poonam', 23, 'ambala')
(573, 'poonam', 26, 'ambala')
(574, 'poonam', 17, 'ambala')
(575, 'poonam', 20, 'ambala')
(576, 'poonam', 26, 'ambala')
(577, 'poonam', 22, 'ambala')
(578, 'poonam', 23, 'ambala')
(579, 'poonam', 23, 'ambala')
(580, 'poonam', 17, 'ambala')
(581, 'poonam', 23, 'ambala')
(582, 'poonam', 29, 'ambala')
(583, 'poonam', 21, 'ambala')
(584, 'poonam', 27, 'ambala')
(585, 'poonam', 19, 'ambala')
(586, 'poonam', 21, 'ambala')
(587, 'poonam', 28, 'ambala')
(588, 'poonam', 17, 'ambala')
(589, 'poonam', 23, 'ambala')
(590, 'poonam', 22, 'ambala')
(591, 'poonam', 29, 'ambala')
(592, 'poonam', 19, 'ambala')
(593, 'poonam', 25, 'ambala')
(594, 'poonam', 28, 'ambala')
(595, 'poonam', 27, 'ambala')
(596, 'poonam', 22, 'ambala')
(597, 'poonam', 24, 'ambala')
(598, 'poonam', 17, 'ambala')
(599, 'poonam', 18, 'ambala')
(600, 'poonam', 25, 'ambala')
(601, 'poonam', 26, 'ambala')
(602, 'poonam', 23, 'ambala')
(603, 'poonam', 17, 'ambala')
(604, 'poonam', 20, 'ambala')
(605, 'poonam', 25, 'ambala')
(606, 'poonam', 22, 'ambala')
(607, 'poonam', 17, 'ambala')
(608, 'poonam', 19, 'ambala')
(609, 'poonam', 29, 'ambala')
(610, 'poonam', 25, 'ambala')
(611, 'poonam', 16, 'ambala')
(612, 'poonam', 22, 'ambala')
(613, 'poonam', 25, 'ambala')
(614, 'poonam', 28, 'ambala')
(615, 'poonam', 16, 'ambala')
(616, 'poonam', 26, 'ambala')
(617, 'poonam', 29, 'ambala')
(618, 'poonam', 27, 'ambala')
(619, 'poonam', 21, 'ambala')
(620, 'poonam', 28, 'ambala')
(621, 'poonam', 26, 'ambala')
(622, 'poonam', 17, 'ambala')
(623, 'poonam', 18, 'ambala')
(624, 'poonam', 22, 'ambala')
(625, 'poonam', 22, 'ambala')
(626, 'poonam', 15, 'ambala')
(627, 'poonam', 23, 'ambala')
(628, 'poonam', 18, 'ambala')
(629, 'poonam', 23, 'ambala')
(630, 'poonam', 19, 'ambala')
(631, 'poonam', 15, 'ambala')
(632, 'poonam', 26, 'ambala')
(633, 'poonam', 20, 'ambala')
(634, 'poonam', 22, 'ambala')
(635, 'poonam', 18, 'ambala')
(636, 'poonam', 22, 'ambala')
(637, 'poonam', 29, 'ambala')
(638, 'poonam', 25, 'ambala')
(639, 'poonam', 25, 'ambala')
(640, 'poonam', 19, 'ambala')
(641, 'poonam', 26, 'ambala')
(642, 'poonam', 16, 'ambala')
(643, 'poonam', 23, 'ambala')
(644, 'poonam', 18, 'ambala')
(645, 'poonam', 25, 'ambala')
(646, 'poonam', 25, 'ambala')
(647, 'poonam', 21, 'ambala')
(648, 'poonam', 23, 'ambala')
(649, 'poonam', 27, 'ambala')
(650, 'poonam', 20, 'ambala')
(651, 'poonam', 24, 'ambala')
(652, 'poonam', 26, 'ambala')
(653, 'poonam', 21, 'ambala')
(654, 'poonam', 29, 'ambala')
(655, 'poonam', 18, 'ambala')
(656, 'poonam', 26, 'ambala')
(657, 'poonam', 21, 'ambala')
(658, 'poonam', 27, 'ambala')
(659, 'poonam', 17, 'ambala')
(660, 'poonam', 24, 'ambala')
(661, 'poonam', 22, 'ambala')
(662, 'poonam', 20, 'ambala')
(663, 'poonam', 20, 'ambala')
(664, 'poonam', 23, 'ambala')
(665, 'poonam', 24, 'ambala')
(666, 'poonam', 22, 'ambala')
(667, 'poonam', 20, 'ambala')
(668, 'poonam', 25, 'ambala')
(669, 'poonam', 25, 'ambala')
(670, 'poonam', 17, 'ambala')

In [122]:
df = pd.DataFrame(results)

In [123]:
df

          0       1   2       3
0         1  poonam  29  ambala
1         2  poonam  18  ambala
2         3  poonam  27  ambala
3         4  poonam  15  ambala
4         5  poonam  28  ambala
...     ...     ...  ..     ...
9995   9996  poonam  15  ambala
9996   9997  poonam  26  ambala
9997   9998  poonam  22  ambala
9998   9999  poonam  15  ambala
9999  10000  poonam  18  ambala

[10000 rows x 4 columns]

In [124]:
df.to_csv("SQL_lite_use",index=False)